/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedProfessoresRouteImport } from './routes/_authenticated/professores'
import { Route as AuthenticatedQuadroRouteImport } from './routes/_authenticated/quadro'
import { Route as AuthenticatedTurmasRouteImport } from './routes/_authenticated/turmas'
import { Route as AuthenticatedAlunosIndexRouteImport } from './routes/_authenticated/alunos/index'
import { Route as AuthenticatedAlunosIdRouteImport } from './routes/_authenticated/alunos/$id'
import { Route as AuthenticatedModalidadesIndexRouteImport } from './routes/_authenticated/modalidades/index'
import { Route as AuthenticatedModalidadesIdRouteImport } from './routes/_authenticated/modalidades/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfessoresRoute =
  AuthenticatedProfessoresRouteImport.update({
    id: '/professores',
    path: '/professores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuadroRoute = AuthenticatedQuadroRouteImport.update({
  id: '/quadro',
  path: '/quadro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTurmasRoute = AuthenticatedTurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlunosIndexRoute =
  AuthenticatedAlunosIndexRouteImport.update({
    id: '/alunos/',
    path: '/alunos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlunosIdRoute = AuthenticatedAlunosIdRouteImport.update({
  id: '/alunos/$id',
  path: '/alunos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModalidadesIndexRoute =
  AuthenticatedModalidadesIndexRouteImport.update({
    id: '/modalidades/',
    path: '/modalidades/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModalidadesIdRoute =
  AuthenticatedModalidadesIdRouteImport.update({
    id: '/modalidades/$id',
    path: '/modalidades/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/professores': typeof AuthenticatedProfessoresRoute
  '/quadro': typeof AuthenticatedQuadroRoute
  '/turmas': typeof AuthenticatedTurmasRoute
  '/alunos/$id': typeof AuthenticatedAlunosIdRoute
  '/modalidades/$id': typeof AuthenticatedModalidadesIdRoute
  '/alunos/': typeof AuthenticatedAlunosIndexRoute
  '/modalidades/': typeof AuthenticatedModalidadesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/professores': typeof AuthenticatedProfessoresRoute
  '/quadro': typeof AuthenticatedQuadroRoute
  '/turmas': typeof AuthenticatedTurmasRoute
  '/alunos/$id': typeof AuthenticatedAlunosIdRoute
  '/modalidades/$id': typeof AuthenticatedModalidadesIdRoute
  '/alunos': typeof AuthenticatedAlunosIndexRoute
  '/modalidades': typeof AuthenticatedModalidadesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/professores': typeof AuthenticatedProfessoresRoute
  '/_authenticated/quadro': typeof AuthenticatedQuadroRoute
  '/_authenticated/turmas': typeof AuthenticatedTurmasRoute
  '/_authenticated/alunos/$id': typeof AuthenticatedAlunosIdRoute
  '/_authenticated/modalidades/$id': typeof AuthenticatedModalidadesIdRoute
  '/_authenticated/alunos/': typeof AuthenticatedAlunosIndexRoute
  '/_authenticated/modalidades/': typeof AuthenticatedModalidadesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/painel'
    | '/professores'
    | '/quadro'
    | '/turmas'
    | '/alunos/$id'
    | '/modalidades/$id'
    | '/alunos/'
    | '/modalidades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/painel'
    | '/professores'
    | '/quadro'
    | '/turmas'
    | '/alunos/$id'
    | '/modalidades/$id'
    | '/alunos'
    | '/modalidades'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/painel'
    | '/_authenticated/professores'
    | '/_authenticated/quadro'
    | '/_authenticated/turmas'
    | '/_authenticated/alunos/$id'
    | '/_authenticated/modalidades/$id'
    | '/_authenticated/alunos/'
    | '/_authenticated/modalidades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/professores': {
      id: '/_authenticated/professores'
      path: '/professores'
      fullPath: '/professores'
      preLoaderRoute: typeof AuthenticatedProfessoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quadro': {
      id: '/_authenticated/quadro'
      path: '/quadro'
      fullPath: '/quadro'
      preLoaderRoute: typeof AuthenticatedQuadroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/turmas': {
      id: '/_authenticated/turmas'
      path: '/turmas'
      fullPath: '/turmas'
      preLoaderRoute: typeof AuthenticatedTurmasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alunos/': {
      id: '/_authenticated/alunos/'
      path: '/alunos'
      fullPath: '/alunos/'
      preLoaderRoute: typeof AuthenticatedAlunosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alunos/$id': {
      id: '/_authenticated/alunos/$id'
      path: '/alunos/$id'
      fullPath: '/alunos/$id'
      preLoaderRoute: typeof AuthenticatedAlunosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modalidades/': {
      id: '/_authenticated/modalidades/'
      path: '/modalidades'
      fullPath: '/modalidades/'
      preLoaderRoute: typeof AuthenticatedModalidadesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modalidades/$id': {
      id: '/_authenticated/modalidades/$id'
      path: '/modalidades/$id'
      fullPath: '/modalidades/$id'
      preLoaderRoute: typeof AuthenticatedModalidadesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedProfessoresRoute: typeof AuthenticatedProfessoresRoute
  AuthenticatedQuadroRoute: typeof AuthenticatedQuadroRoute
  AuthenticatedTurmasRoute: typeof AuthenticatedTurmasRoute
  AuthenticatedAlunosIdRoute: typeof AuthenticatedAlunosIdRoute
  AuthenticatedModalidadesIdRoute: typeof AuthenticatedModalidadesIdRoute
  AuthenticatedAlunosIndexRoute: typeof AuthenticatedAlunosIndexRoute
  AuthenticatedModalidadesIndexRoute: typeof AuthenticatedModalidadesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedProfessoresRoute: AuthenticatedProfessoresRoute,
  AuthenticatedQuadroRoute: AuthenticatedQuadroRoute,
  AuthenticatedTurmasRoute: AuthenticatedTurmasRoute,
  AuthenticatedAlunosIdRoute: AuthenticatedAlunosIdRoute,
  AuthenticatedModalidadesIdRoute: AuthenticatedModalidadesIdRoute,
  AuthenticatedAlunosIndexRoute: AuthenticatedAlunosIndexRoute,
  AuthenticatedModalidadesIndexRoute: AuthenticatedModalidadesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
